force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Informe</label>
    <nameField>
        <displayFormat>Boletín-{0000}</displayFormat>
        <label>Boletín número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletin__c/fields/AAAPE__c.field-meta.xml
<CustomField>
    <fullName>AAAPE__c</fullName>
    <label>Aprender a aprender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Calificaciones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/AAAPEForm__c.field-meta.xml
<CustomField>
    <fullName>AAAPEForm__c</fullName>
    <formula>CASE( AAAPE__c , &apos;Excelente&apos;, &apos;Evidente iniciativa para aprender, conoce de las propias fortalezas y debilidades para establecer objetivos realizables, organizarse para cumplirlos pudiendo evaluar y reflexionar sobre su proceso de aprendizaje.&apos;, &apos;Muy bueno&apos;, &apos;Muy buena iniciativa para aprender y organizarse para establecer objetivos realizables en base a sus propias fortalezas y debilidades. Aún cuesta sostener el trabajo para alcanzarlos, evaluar el proceso e identificar posibles mejoras.&apos;, &apos;Bueno&apos;, &apos;Buena iniciativa para aprender y organizarse. En general establece objetivos realizables que podrían ajustarse mejor según sus necesidades. Reflexionar sobre el propio proceso de aprendizaje podría contribuir a que sean sostenibles.&apos;, &apos;Regular&apos;, &apos;En ocasiones tiene iniciativa para incorporar nuevos aprendizajes. Todavía necesita conocerse más para encontrar la forma de organizarse, identificar objetivos realizables y organizarse para sostenerlos en el tiempo.&apos;, &apos;Mejorable&apos;, &apos;Necesita incentivo/s externo/s para iniciar aprendizajes y los objetivos propuestos son difíciles de cumplir y sostener.&apos;, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/AAASE__c.field-meta.xml
<CustomField>
    <fullName>AAASE__c</fullName>
    <label>Aprender a aprender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Calificaciones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/AyCPE__c.field-meta.xml
<CustomField>
    <fullName>AyCPE__c</fullName>
    <label>Análisis y comprensión de la información</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Calificaciones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/AyCPEForm__c.field-meta.xml
<CustomField>
    <fullName>AyCPEForm__c</fullName>
    <formula>CASE( AyCPE__c , &apos;Excelente&apos;, &apos;Evidente capacidad para comprender textos leídos y extraer información relevante de diferentes fuentes a partir de identificar conceptos y establecer relaciones entre ellos, elaborar conclusiones y desarrollar ideas transferibles a otros ámbitos.&apos;, &apos;Muy bueno&apos;, &apos;Muy buena capacidad para comprender textos leídos y extraer información relevante de diferentes fuentes. Logra identificar conceptos, establecer relaciones, elaborar conclusiones y desarrollar ideas.&apos;, &apos;Bueno&apos;, &apos;Buena capacidad para comprender textos leídos y extraer información relevante. Logra identificar conceptos y tiene dificultades para establecer relaciones entre ellos y elaborar conclusiones o desarrollar ideas.&apos;, &apos;Regular&apos;, &apos;Ocasionalmente logra comprender textos leídos y extraer información relevante. Tiene dificultades para identificar conceptos y establecer relaciones. A veces puede elaborar conclusiones o desarrollar ideas.&apos;, &apos;Mejorable&apos;, &apos;Todavía encuentra dificultades para comprender los textos que lee. No logra seleccionar fuentes e identificar conceptos para extraer información y elaborar conclusiones o desarrollar ideas.&apos;, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/CAPE__c.field-meta.xml
<CustomField>
    <fullName>CAPE__c</fullName>
    <label>Ciudadanía responsable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Calificaciones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/CAPEForm__c.field-meta.xml
<CustomField>
    <fullName>CAPEForm__c</fullName>
    <formula>CASE(  CAPE__c , &apos;Excelente&apos;, &apos;Asume responsabilidades y se involucra con su comunidad. Participa activamente y promueve el compromiso por el bien común.&apos;, &apos;Muy bueno&apos;, &apos;Generalmente es responsable. Responde por sus actos a los compromisos asumidos y contribuye al bien común.&apos;, &apos;Bueno&apos;, &apos;Asume responsabilidades y compromisos básicos que le corresponden. Reconoce las implicancias de sus actos y de lo demás y, en algunas ocasiones, interviene.&apos;, &apos;Regular&apos;, &apos;No siempre asume sus responsabilidades. Tiene dificultades para intervenir y reconocer las implicancias de sus actos y de los demás.&apos;, &apos;Mejorable&apos;, &apos;Evita responsabilidades y no reconoce las implicancias de los propios actos. Muestra cierta indiferencia hacia su comunidad.&apos;, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/CPE__c.field-meta.xml
<CustomField>
    <fullName>CPE__c</fullName>
    <label>Comunicación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Calificaciones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/CPEForm__c.field-meta.xml
<CustomField>
    <fullName>CPEForm__c</fullName>
    <formula>CASE( CPE__c , &apos;Excelente&apos;, &apos;Destacada capacidad para comunicarse de manera efectiva, expresar y comprender mensajes en diferentes contextos y según distintos propósitos. Utiliza variedad de soportes, un lenguaje verbal y no verbal apropiado.&apos;, &apos;Muy bueno&apos;, &apos;Muy buena capacidad para comunicarse y expresarse en forma clara y adecuada, y comprender mensajes en la mayoría de las situaciones comunicativas.&apos;, &apos;Bueno&apos;, &apos;Buena capacidad para comunicarse y expresarse en forma clara y adecuada y comprender mensajes en algunas situaciones comunicativas.&apos;, &apos;Regular&apos;, &apos;No siempre se expresa en forma efectiva y tiene algunas dificultades para comprender mensajes recibidos. En ocasiones no logra comunicar abiertamente su posición o se comunica con un lenguaje inapropiado.&apos;, &apos;Mejorable&apos;, &apos;Generalmente tiene dificultades para hacerse entender y expresarse, así como para comprender el mensaje transmitido.&apos;, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/OyPPE__c.field-meta.xml
<CustomField>
    <fullName>OyPPE__c</fullName>
    <label>Organización y planificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Calificaciones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/OyPPEForm__c.field-meta.xml
<CustomField>
    <fullName>OyPPEForm__c</fullName>
    <formula>CASE( OyPPE__c , &apos;Excelente&apos;, &apos;Evidente capacidad para autogestionar, anticipar y planificar tareas eficientemente. Sabe proponerse metas realizables en el tiempo y establecer prioridades. Identifica los recursos necesarios y prevee soluciones ante posibles obstáculos.&apos;, &apos;Muy bueno&apos;, &apos;Muy buena capacidad para anticipar y organizar su trabajo de forma, establecer metas y cumplirlas en tiempo y forma. En ocasiones solicita ayuda para establecer prioridades y/o encontrar soluciones frente a obstáculos imprevistos.&apos;, &apos;Bueno&apos;, &apos;En general logra organizarse con sus tareas y cumplirlas. No siempre logra anticiparse a los tiempos y recursos necesarios. Suele necesitar ayuda para establecer prioridades y seguimiento para llegar a tiempo.&apos;, &apos;Regular&apos;, &apos;Ocasionalmente cumple con sus tareas sin tener un registro de las acciones necesarias para lograrlo. Frecuentemente necesita un seguimiento que impulse su accionar.&apos;, &apos;Mejorable&apos;, &apos;Tiende a trabajar en forma reactiva. Necesita orientación y seguimiento permanente para realizar sus tareas.&apos;,NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/PCPE__c.field-meta.xml
<CustomField>
    <fullName>PCPE__c</fullName>
    <label>Pensamiento crítico</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Calificaciones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/PCPEForm__c.field-meta.xml
<CustomField>
    <fullName>PCPEForm__c</fullName>
    <formula>CASE( PCPE__c , &apos;Excelente&apos;,  &apos;Continuamente es capaz de adoptar una postura propia sobre diversas situaciones o problemáticas fundada en el análisis de información considerando distintas variables, perspectivas y argumentos, y tomar decisiones consecuentes respetando otras opiniones.&apos;, &apos;Muy bueno&apos;, &apos;Frecuentemente es capaz de adoptar una postura propia sobre una problemática o situación determinada fundada en el análisis de información, construir juicios razonados y tomar decisiones consecuentes respetando otras opiniones&apos;, &apos;Bueno&apos;, &apos;En ocasiones es capaz de adoptar una postura propia respecto de una problemática o situación determinada fundada en el análisis de información y tomar decisiones consecuentes respetando otras opiniones&apos;, &apos;Regular&apos;, &apos;Muestra dificultades para reflexionar y adoptar una postura propia respecto de una problemática o situación determinada y tomar decisiones consecuentes respetando otras opiniones.&apos;, &apos;Mejorable&apos;, &apos;Aún no logra reflexionar ni adoptar una postura propia y fundada respecto de una problemática o situación determinada.&apos;, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/TcOPE__c.field-meta.xml
<CustomField>
    <fullName>TcOPE__c</fullName>
    <label>Trabajo con otros</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Calificaciones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boletin__c/fields/TcOPEForm__c.field-meta.xml
<CustomField>
    <fullName>TcOPEForm__c</fullName>
    <formula>CASE( TcOPE__c, &apos;Excelente&apos;, &apos;Siempre presta atención a las necesidades de los otros y promueve el funcionamiento del grupo en pos de los objetivos comunes integrando las distintas opiniones.&apos;, &apos;Muy bueno&apos;, &apos;Muestra compromiso en el trabajo con otros. Presta atención a las necesidades de los demás y colabora con el logro de los objetivos comunes.&apos;, &apos;Bueno&apos;, &apos;A menudo colabora en el trabajo con otros. Reconoce las necesidades de los demás.&apos;, &apos;Regular&apos;, &apos;En situaciones de trabajo con otros solo colabora cuando le es requerido o cuando es necesario. No siempre reconoce las necesidades de los otros.&apos;, &apos;Mejorable&apos;, &apos;Muestra baja predisposición a la colaboración y resistencia a las dinámicas grupales. Es intransigente y se ofende cuando no siguen su idea.&apos;, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descripción</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calificacion__c/fields/Primer_trimestre__c.field-meta.xml
<CustomField>
    <fullName>Primer_trimestre__c</fullName>
    <description>Nota de la materia en el primer trimestre.</description>
    <label>Evaluación 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calificacion__c/fields/Segundo_trimestre__c.field-meta.xml
<CustomField>
    <fullName>Segundo_trimestre__c</fullName>
    <description>Nota de la materia en el segundo trimestre.</description>
    <label>Evaluación 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calificacion__c/fields/Tercer_trimestre__c.field-meta.xml
<CustomField>
    <fullName>Tercer_trimestre__c</fullName>
    <description>Nota de la materia en el tercer trimestre.</description>
    <label>Evaluación 3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inasistencia__c/fields/Primer_trimestre__c.field-meta.xml
<CustomField>
    <fullName>Primer_trimestre__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Evaluación 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inasistencia__c/fields/Segundo_trimestre__c.field-meta.xml
<CustomField>
    <fullName>Segundo_trimestre__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Evaluación 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inasistencia__c/fields/Tercer_trimestre__c.field-meta.xml
<CustomField>
    <fullName>Tercer_trimestre__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Evaluación 3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Calificaciones.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Excelente</fullName>
    </customValue>
    <customValue>
        <fullName>Muy bueno</fullName>
    </customValue>
    <customValue>
        <fullName>Bueno</fullName>
    </customValue>
    <customValue>
        <fullName>Regular</fullName>
    </customValue>
    <customValue>
        <fullName>Mejorable</fullName>
    </customValue>
    <customValue>
        <fullName>No evaluado</fullName>
    </customValue>
    <masterLabel>Calificaciones</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BoletinDataService.cls
public with sharing class BoletinDataService {

    @AuraEnabled(Cacheable=true)
    public static List<Calificacion__c> getCalificaciones(String boletinId) {
        List<Calificacion__c> listaDeCalificaciones = [SELECT Id, Materia__r.Name, Primer_trimestre__c, Segundo_trimestre__c, Tercer_trimestre__c, Final__c, Estado__c FROM Calificacion__c WHERE Boletin__c = :boletinId];
        return listaDeCalificaciones;
    }

    @AuraEnabled(Cacheable=true)
    public static List<Inasistencia__c> getInasistencias(String boletinId) {
        List<Inasistencia__c> listaDeInasistencias = [SELECT Id, Primer_trimestre__c, Segundo_trimestre__c, Tercer_trimestre__c, Boletin__c, Acumulado_Anual__c FROM Inasistencia__c
                                                      WHERE Boletin__c = :boletinId];
        return listaDeInasistencias;
    }

    @AuraEnabled(Cacheable=true)
    public static Boletin__c getCapacidades(Id recordId) {
        return [SELECT
                AAAPE__c, AAAPEForm__c,
                CPE__c, CPEForm__c,
                AyCPE__c, AyCPEForm__c,
                PCPE__c, PCPEForm__c,
                OyPPE__c, OyPPEForm__c,
                TcOPE__c, TcOPEForm__c,
                CAPE__c, CAPEForm__c,
                AAASE__c, AAASEForm__c,
                CSE__c, CSEForm__c,
                AyCSE__c, AyCSEForm__c,
                PCSE__c, PCSEForm__c,
                OYPSE__c, OyPSEForm__c,
                TcOSE__c, TcOSEForm__c,
                CASE__c, CASEForm__c,
                Eval1_completa__c
                FROM Boletin__c
                WHERE Id = :recordId
                LIMIT 1
                ];
    }
    
    @AuraEnabled
    public static List<Calificacion__c> getListCalificaciones(List<ID> boletinIdList) {
        List<Calificacion__c> listaDeCalificaciones = [SELECT Id, Materia__r.Name, Primer_trimestre__c, Segundo_trimestre__c, Tercer_trimestre__c, Final__c, Boletin__c, Boletin__r.Alumno__c FROM Calificacion__c
                                                       WHERE Boletin__c IN :boletinIdList];
        return listaDeCalificaciones;
    }
    
    @AuraEnabled
    public static List<Inasistencia__c> getListInasistencias(List<ID> boletinIdList) {
        List<Inasistencia__c> listaDeInasistencias = [SELECT Id, Primer_trimestre__c, Segundo_trimestre__c, Tercer_trimestre__c, Boletin__r.Alumno__c, Acumulado_Anual__c FROM Inasistencia__c
                                                      WHERE Boletin__c IN :boletinIdList];
        return listaDeInasistencias;
    }

    @AuraEnabled
    public static String updateCalificacion(List<Calificacion__c> data) {
        try {
            update data;
            return 'Boletín actualizado';
        }
        catch(exception error) {
            return error.getMessage();
        }
        
    }

    @AuraEnabled
    public static String updateInasistencia(List<Inasistencia__c> data) {
        try {
            update data;
            return 'Boletín actualizado';
        }
        catch(exception error) {
            return error.getMessage();
        }
    }

    @AuraEnabled
    public static String updateCapacidades(String data) {
        try {
            Boletin__c boletin = (Boletin__c)JSON.deserializeStrict(data, Boletin__c.class);
            update boletin;
            return 'Boletín actualizado';
        }
        catch(exception error) {
            return error.getMessage();
        }
    }
}