force-app/main/default/objects/Account/fields/Modalidad__c.field-meta.xml
<CustomField>
    <fullName>Modalidad__c</fullName>
    <label>Modalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Técnica</fullName>
            </value>
            <value>
                <fullName>Orientada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asistencia_a_Espacio_Educativo__c/Asistencia_a_Espacio_Educativo__c.object-meta.xml
<CustomObject>
    <label>Asistencia a Espacio Educativo</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Registro Asistencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asistencia a Espacios Educativos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asistencia_a_Espacio_Educativo__c/fields/Boletin__c.field-meta.xml
<CustomField>
    <fullName>Boletin__c</fullName>
    <label>Boletin</label>
    <referenceTo>Boletin__c</referenceTo>
    <relationshipLabel>Asistencia a Espacios Educativos</relationshipLabel>
    <relationshipName>Asistencia_a_Espacios_Educativos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Informe</label>
    <nameField>
        <displayFormat>Boletín-{0000}</displayFormat>
        <label>Boletín número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletin__c/fields/Alumno__c.field-meta.xml
<CustomField>
    <fullName>Alumno__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El contacto seleccionado debe ser un Becario</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NPSP_Becarios</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Boletines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/A_o_de_Ingreso_a_Reciduca__c.field-meta.xml
<CustomField>
    <fullName>A_o_de_Ingreso_a_Reciduca__c</fullName>
    <label>Año de Ingreso a Reciduca</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/A_o_que_cursa__c.field-meta.xml
<CustomField>
    <fullName>A_o_que_cursa__c</fullName>
    <label>Año que cursa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5°</fullName>
                <default>true</default>
                <label>5°</label>
            </value>
            <value>
                <fullName>6°</fullName>
            </value>
            <value>
                <fullName>7°</fullName>
            </value>
            <value>
                <fullName>No Corresponde</fullName>
                <isActive>false</isActive>
                <label>No Corresponde</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Padrino__c.field-meta.xml
<CustomField>
    <fullName>Padrino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Padrino</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contactos</relationshipLabel>
    <relationshipName>Contactos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Seguimiento_Educativo__c.field-meta.xml
<CustomField>
    <fullName>Seguimiento_Educativo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seguimiento Educativo</label>
    <referenceTo>Seguimiento_Educativo__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Becarios.recordType-meta.xml
<RecordType>
    <fullName>Becarios</fullName>
    <active>true</active>
    <label>Becarios</label>
</RecordType>

force-app/main/default/objects/Pertenencia_a_Programas__c/Pertenencia_a_Programas__c.object-meta.xml
<CustomObject>
    <description>Es la pertencia a los programas de Prácticas Educativas Nivel 0, 1 o Nivel 2</description>
    <label>Pertenencia a Programa</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nombre de Pertenencia a CFC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pertenencia a Programa Educativo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pertenencia_a_Programas__c/fields/Alumno__c.field-meta.xml
<CustomField>
    <fullName>Alumno__c</fullName>
    <label>Alumno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Pertenencias_a_Programas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pertenencia_a_Programas__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <label>Programa</label>
    <referenceTo>Programa__c</referenceTo>
    <relationshipName>Pertenencias_a_Programas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seguimiento_Educativo__c/Seguimiento_Educativo__c.object-meta.xml
<CustomObject>
    <label>Seguimiento Educativo</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nombre de Seguimiento Educativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seguimiento Educativo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seguimiento_Educativo__c/fields/Alumno__c.field-meta.xml
<CustomField>
    <fullName>Alumno__c</fullName>
    <label>Alumno</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>NPSP Becarios</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Seguimientos Educativos</relationshipLabel>
    <relationshipName>Seguimientos_Educativos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seguimiento_Educativo__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programa</label>
    <referenceTo>Programa__c</referenceTo>
    <relationshipLabel>Seguimiento Educativo</relationshipLabel>
    <relationshipName>Seguimiento_Educativo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactViewPDFContTest.cls
@isTest
public with sharing class ContactViewPDFContTest 
{
    @isTest
    public static void testContactNPSPBecariosNivelCero()
    {
        test.startTest();
        
        Contact alumno = setupAlumno('Técnica', '5°');
        Boletin__c boletin = [SELECT Id FROM Boletin__c WHERE Alumno__c =: alumno.Id];

        Inasistencia__c inasistencia = new Inasistencia__c();
        inasistencia.Boletin__c = boletin.Id;
        insert inasistencia;

        Programa__c prog = TestDataFactory.createProgramaNivelCero('programa nivel 0');
        Pertenencia_a_Programas__c pert = TestDataFactory.createPertenencia(alumno.Id, prog.Id);
        Seguimiento_Educativo__c seguimiento = TestDataFactory.createSeguimiento(alumno.Id, prog.Id);
        List<Asistencia_a_Espacio_Educativo__c> asistenciaEspacio = TestDataFactory.createAsistenciaEspacios(boletin.Id);

        ApexPages.StandardController sc = new ApexPages.StandardController(alumno);
        ContactViewPDFController controller = new ContactViewPDFController(sc);
        
        test.stopTest();
        
        System.assertNotEquals(controller.resultList[0].boletin,null);
        System.assertNotEquals(controller.resultList[0].listaDeCalificaciones,null);
        System.assertNotEquals(controller.resultList[0].listaDeInasistencias,null);
        System.assertNotEquals(controller.resultList[0].programa,null);
        System.assertNotEquals(controller.resultList[0].ImagenDeAlumno,null);
        System.assertNotEquals(controller.resultList[0].thecontact,null);
        System.assertNotEquals(controller.resultList[0].capacidades,null);
        System.assertNotEquals(controller.resultList[0].actividadesPrograma, null);
        System.assertNotEquals(controller.resultList[0].asistenciaAEspacios, null);
        System.assertEquals(controller.boleano, false);
    }

    @isTest
    public static void testContactNPSPBecariosNivelUno()
    {
        test.startTest();
        
        Contact alumno = setupAlumno('Técnica', '6°');
        Boletin__c boletin = [SELECT Id FROM Boletin__c WHERE Alumno__c =: alumno.Id];

        Inasistencia__c inasistencia = new Inasistencia__c();
        inasistencia.Boletin__c = boletin.Id;
        insert inasistencia;

        Programa__c prog = TestDataFactory.createProgramaNivelUno('programa nivel 1');
        Pertenencia_a_Programas__c pert = TestDataFactory.createPertenencia(alumno.Id, prog.Id);
        Seguimiento_Educativo__c seguimiento = TestDataFactory.createSeguimiento(alumno.Id, prog.Id);
        List<Asistencia_a_Espacio_Educativo__c> asistenciaEspacio = TestDataFactory.createAsistenciaEspacios(boletin.Id);

        ApexPages.StandardController sc = new ApexPages.StandardController(alumno);
        ContactViewPDFController controller = new ContactViewPDFController(sc);
        
        test.stopTest();
        
        System.assertNotEquals(controller.resultList[0].boletin,null);
        System.assertNotEquals(controller.resultList[0].listaDeCalificaciones,null);
        System.assertNotEquals(controller.resultList[0].listaDeInasistencias,null);
        System.assertNotEquals(controller.resultList[0].programa,null);
        System.assertNotEquals(controller.resultList[0].ImagenDeAlumno,null);
        System.assertNotEquals(controller.resultList[0].thecontact,null);
        System.assertNotEquals(controller.resultList[0].capacidades,null);
        System.assertNotEquals(controller.resultList[0].actividadesPrograma, null);
        System.assertNotEquals(controller.resultList[0].asistenciaAEspacios, null);
        System.assertEquals(controller.boleano, false);
    }

    @isTest
    public static void testContactNPSPBecariosNivelDosOrientada()
    {
        test.startTest();
        
        Contact alumno = setupAlumno('Orientada', '6°');
        Boletin__c boletin = [SELECT Id FROM Boletin__c WHERE Alumno__c =: alumno.Id];

        Inasistencia__c inasistencia = new Inasistencia__c();
        inasistencia.Boletin__c = boletin.Id;
        insert inasistencia;

        Programa__c prog = TestDataFactory.createProgramaNivelDos('programa nivel 2');
        Pertenencia_a_Programas__c pert = TestDataFactory.createPertenencia(alumno.Id, prog.Id);
        Seguimiento_Educativo__c seguimiento = TestDataFactory.createSeguimiento(alumno.Id, prog.Id);
        List<Asistencia_a_Espacio_Educativo__c> asistenciaEspacio = TestDataFactory.createAsistenciaEspacios(boletin.Id);

        ApexPages.StandardController sc = new ApexPages.StandardController(alumno);
        ContactViewPDFController controller = new ContactViewPDFController(sc);
        
        test.stopTest();
        
        System.assertNotEquals(controller.resultList[0].boletin,null);
        System.assertNotEquals(controller.resultList[0].listaDeCalificaciones,null);
        System.assertNotEquals(controller.resultList[0].listaDeInasistencias,null);
        System.assertNotEquals(controller.resultList[0].programa,null);
        System.assertNotEquals(controller.resultList[0].ImagenDeAlumno,null);
        System.assertNotEquals(controller.resultList[0].thecontact,null);
        System.assertNotEquals(controller.resultList[0].capacidades,null);
        System.assertNotEquals(controller.resultList[0].actividadesPrograma, null);
        System.assertNotEquals(controller.resultList[0].asistenciaAEspacios, null);
        System.assertEquals(controller.boleano, false);
    }

    @isTest
    public static void testContactNPSPBecariosNivelDosTecnica()
    {
        test.startTest();
        
        Contact alumno = setupAlumno('Técnica', '7°');
        Boletin__c boletin = [SELECT Id FROM Boletin__c WHERE Alumno__c =: alumno.Id];

        Inasistencia__c inasistencia = new Inasistencia__c();
        inasistencia.Boletin__c = boletin.Id;
        insert inasistencia;

        Programa__c prog = TestDataFactory.createProgramaNivelDos('programa nivel 2');
        Pertenencia_a_Programas__c pert = TestDataFactory.createPertenencia(alumno.Id, prog.Id);
        Seguimiento_Educativo__c seguimiento = TestDataFactory.createSeguimiento(alumno.Id, prog.Id);
        List<Asistencia_a_Espacio_Educativo__c> asistenciaEspacio = TestDataFactory.createAsistenciaEspacios(boletin.Id);

        ApexPages.StandardController sc = new ApexPages.StandardController(alumno);
        ContactViewPDFController controller = new ContactViewPDFController(sc);
        
        test.stopTest();
        
        System.assertNotEquals(controller.resultList[0].boletin,null);
        System.assertNotEquals(controller.resultList[0].listaDeCalificaciones,null);
        System.assertNotEquals(controller.resultList[0].listaDeInasistencias,null);
        System.assertNotEquals(controller.resultList[0].programa,null);
        System.assertNotEquals(controller.resultList[0].ImagenDeAlumno,null);
        System.assertNotEquals(controller.resultList[0].thecontact,null);
        System.assertNotEquals(controller.resultList[0].capacidades,null);
        System.assertNotEquals(controller.resultList[0].actividadesPrograma, null);
        System.assertNotEquals(controller.resultList[0].asistenciaAEspacios, null);
        System.assertEquals(controller.boleano, false);
    }

    @isTest
    public static void testContactNPSPBecariosNivelCeroTecnica()
    {
        test.startTest();
        
        Contact alumno = setupAlumno('Técnica', '5°');
        Boletin__c boletin = [SELECT Id FROM Boletin__c WHERE Alumno__c =: alumno.Id];

        Inasistencia__c inasistencia = new Inasistencia__c();
        inasistencia.Boletin__c = boletin.Id;
        insert inasistencia;

        Programa__c prog = TestDataFactory.createProgramaNivelDos('programa nivel 0');
        Pertenencia_a_Programas__c pert = TestDataFactory.createPertenenciaInactiva(alumno.Id, prog.Id);
        Seguimiento_Educativo__c seguimiento = TestDataFactory.createSeguimiento(alumno.Id, prog.Id);
        List<Asistencia_a_Espacio_Educativo__c> asistenciaEspacio = TestDataFactory.createAsistenciaEspacios(boletin.Id);

        ApexPages.StandardController sc = new ApexPages.StandardController(alumno);
        ContactViewPDFController controller = new ContactViewPDFController(sc);
        
        test.stopTest();
        
        System.assertNotEquals(controller.boleano, false);
    }

    @isTest
    public static void testContactNPSPGenerales()
    {
        test.startTest();
        
        Contact alumno = setupAlumno('Técnica', '6°'); 
        Contact padrino = [SELECT Id FROM Contact WHERE Id =: alumno.Padrino__c];

        Programa__c prog = TestDataFactory.createProgramaNivelUno('programa nivel 1');
        Pertenencia_a_Programas__c pert = TestDataFactory.createPertenencia(alumno.Id, prog.Id);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(padrino);
        ContactViewPDFController controller = new ContactViewPDFController(sc);
        
        test.stopTest();
        
        System.assertNotEquals(controller.resultList[0].boletin,null);
        System.assertNotEquals(controller.resultList[0].listaDeCalificaciones,null);
        System.assertNotEquals(controller.resultList[0].listaDeInasistencias,null);
        System.assertNotEquals(controller.resultList[0].programa,null);
    }

    @isTest
    public static void testContactPDFEscuela()
    {
        test.startTest();
        
        Contact alumno = setupAlumno('Técnica', '6°'); 
        Account escuela = [SELECT Id FROM Account WHERE Id =: alumno.npsp__Primary_Affiliation__c];

        Programa__c prog = TestDataFactory.createProgramaNivelUno('programa nivel 1');
        Pertenencia_a_Programas__c pert = TestDataFactory.createPertenencia(alumno.Id, prog.Id);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(escuela);
        ContactViewPDFController controller = new ContactViewPDFController(sc);
        
        test.stopTest();
        
        System.assertNotEquals(controller.resultList[0].boletin,null);
        System.assertNotEquals(controller.resultList[0].listaDeCalificaciones,null);
        System.assertNotEquals(controller.resultList[0].listaDeInasistencias,null);
        System.assertNotEquals(controller.resultList[0].programa,null);
    }

    //Helper creacion alumno
    private static Contact setupAlumno(String orientacion, String anioQueCursa) {
        DateTime myDateTime = DateTime.now();
        
        //creación de 3 materias
        List<Materia__c> listMaterias = new List<Materia__c>();
        for (Integer i = 0; i < 3; i++) {
            Materia__c materia = new Materia__c(Name='Materia '+ i + myDateTime.millisecond());
            listMaterias.add(materia);
        }
        insert listMaterias;

        //creación de escuela
        id schemaTypeEscuela = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Escuela').getRecordTypeId();
        Account esc = new Account(Name='Escuelita', Modalidad__c = orientacion, RecordTypeId=schemaTypeEscuela);
        insert esc;

        //creación de plan de estudios, con lookup a las materias y la escuela
        List<Plan_de_estudios__c> listPlanEstudio = new List<Plan_de_estudios__c>();
        for (Integer i = 0; i < 3; i++) {
           Plan_de_estudios__c planEstudio = new Plan_de_estudios__c();
           planEstudio.Anio_en_curso__c = anioQueCursa;
           planEstudio.Escuela__c = esc.Id;
           planEstudio.Materia__c = listMaterias[i].Id;
           listPlanEstudio.add(planEstudio);
        }
        insert listPlanEstudio;
        
        //creación de padrino
        id schemaTypeIdPadrino = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('NPSP Contactos Generales').getRecordTypeId();
        Contact padrino = new Contact(
            FirstName = 'Nombre'+myDateTime.millisecond(),
            LastName='Apellido'+myDateTime.millisecond(), 
            RecordTypeId=schemaTypeIdPadrino, 
            Sexo__c='Masculino'
        );
        insert padrino;

        //creación de alumno con padrino asignado
        id schemaTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('NPSP Becarios').getRecordTypeId();
        Contact alumno = new Contact(
            FirstName = 'Nombre'+myDateTime.millisecond(),
            LastName = 'Apellido'+myDateTime.millisecond(), 
            RecordTypeId = schemaTypeId, 
            Sexo__c = 'Masculino',
            A_o_de_Ingreso_a_Reciduca__c = 2003, 
            A_o_que_cursa__c = anioQueCursa, 
            npsp__Primary_Affiliation__c = esc.Id,
            Padrino__c = padrino.Id
            );
        insert alumno;

        ContentVersion imgTest = new ContentVersion();
        imgTest.FirstPublishLocationId = alumno.Id;
        imgTest.Title = 'Test Image';
        imgTest.ContentUrl = 'image test url';
        insert imgTest;

        return alumno;

    }
}