force-app/main/default/objects/Asistencia_a_Espacio_Educativo__c/Asistencia_a_Espacio_Educativo__c.object-meta.xml
<CustomObject>
    <label>Asistencia a Espacio Educativo</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Registro Asistencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asistencia a Espacios Educativos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asistencia_a_Espacio_Educativo__c/fields/Boletin__c.field-meta.xml
<CustomField>
    <fullName>Boletin__c</fullName>
    <label>Boletin</label>
    <referenceTo>Boletin__c</referenceTo>
    <relationshipLabel>Asistencia a Espacios Educativos</relationshipLabel>
    <relationshipName>Asistencia_a_Espacios_Educativos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asistencia_a_Espacio_Educativo__c/fields/Cantidad_de_Encuentros__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Encuentros__c</fullName>
    <inlineHelpText>Cantidad de encuentros que hubo del espacio en el mes seleccionado</inlineHelpText>
    <label>Cantidad de Encuentros</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asistencia_a_Espacio_Educativo__c/fields/Encuentros_Asistidos__c.field-meta.xml
<CustomField>
    <fullName>Encuentros_Asistidos__c</fullName>
    <inlineHelpText>Cantidad de veces que asistió al encuentro del espacio en el mes seleccionado</inlineHelpText>
    <label>Encuentros Asistidos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asistencia_a_Espacio_Educativo__c/fields/Espacio_Educativo__c.field-meta.xml
<CustomField>
    <fullName>Espacio_Educativo__c</fullName>
    <label>Espacio Educativo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acompañamiento Educativo</fullName>
            </value>
            <value>
                <fullName>Desarrollo Personal</fullName>
            </value>
            <value>
                <fullName>Proyecto CAS</fullName>
            </value>
            <value>
                <fullName>Capacitacion</fullName>
            </value>
            <value>
                <fullName>Practica Educativa</fullName>
            </value>
            <value>
                <fullName>Acompañamiento Personal</fullName>
                <isActive>false</isActive>
                <label>Acompañamiento Personal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asistencia_a_Espacio_Educativo__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <label>Mes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mayo</fullName>
            </value>
            <value>
                <fullName>Junio</fullName>
            </value>
            <value>
                <fullName>Julio</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Septiembre</fullName>
            </value>
            <value>
                <fullName>Octubre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Boletin__c/Boletin__c.object-meta.xml
<CustomObject>
    <label>Informe</label>
    <nameField>
        <displayFormat>Boletín-{0000}</displayFormat>
        <label>Boletín número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Boletin__c/fields/Alumno__c.field-meta.xml
<CustomField>
    <fullName>Alumno__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El contacto seleccionado debe ser un Becario</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NPSP_Becarios</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Boletines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pertenencia_a_Programas__c/Pertenencia_a_Programas__c.object-meta.xml
<CustomObject>
    <description>Es la pertencia a los programas de Prácticas Educativas Nivel 0, 1 o Nivel 2</description>
    <label>Pertenencia a Programa</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nombre de Pertenencia a CFC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pertenencia a Programa Educativo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pertenencia_a_Programas__c/fields/Alumno__c.field-meta.xml
<CustomField>
    <fullName>Alumno__c</fullName>
    <label>Alumno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Pertenencias_a_Programas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pertenencia_a_Programas__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pertenencia_a_Programas__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <label>Programa</label>
    <referenceTo>Programa__c</referenceTo>
    <relationshipName>Pertenencias_a_Programas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Programa__c/fields/N_0_Escuela_Tecnica__c.field-meta.xml
<CustomField>
    <fullName>N_0_Escuela_Tecnica__c</fullName>
    <inlineHelpText>Texto sobre Actividades del Programa</inlineHelpText>
    <label>N°0 Escuela Tecnica</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Programa__c/fields/N_1_Escuela_Tecnica_Orientada__c.field-meta.xml
<CustomField>
    <fullName>N_1_Escuela_Tecnica_Orientada__c</fullName>
    <inlineHelpText>Texto de Actividades del Programa</inlineHelpText>
    <label>N°1 Escuela Tecnica/Orientada</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Programa__c/fields/N_2_Escuela_Orientada__c.field-meta.xml
<CustomField>
    <fullName>N_2_Escuela_Orientada__c</fullName>
    <label>N°2 Escuela Orientada</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Programa__c/fields/N_2_Escuela_Tecnica__c.field-meta.xml
<CustomField>
    <fullName>N_2_Escuela_Tecnica__c</fullName>
    <label>N°2 Escuela Tecnica</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Seguimiento_Educativo__c/Seguimiento_Educativo__c.object-meta.xml
<CustomObject>
    <label>Seguimiento Educativo</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Nombre de Seguimiento Educativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seguimiento Educativo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seguimiento_Educativo__c/fields/Alumno__c.field-meta.xml
<CustomField>
    <fullName>Alumno__c</fullName>
    <label>Alumno</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>NPSP Becarios</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Seguimientos Educativos</relationshipLabel>
    <relationshipName>Seguimientos_Educativos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seguimiento_Educativo__c/fields/Cantidad_de_Materias_Previas__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Materias_Previas__c</fullName>
    <inlineHelpText>Si no debe ninguna materia, completar con 0</inlineHelpText>
    <label>Cantidad de Materias Previas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seguimiento_Educativo__c/fields/Cu_ntas__c.field-meta.xml
<CustomField>
    <fullName>Cu_ntas__c</fullName>
    <inlineHelpText>Si no debe ninguna materia, poner 0</inlineHelpText>
    <label>¿Cuántas?</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seguimiento_Educativo__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cursando 5° año</fullName>
            </value>
            <value>
                <fullName>Cursando 6° año</fullName>
            </value>
            <value>
                <fullName>Cursando 7° año</fullName>
            </value>
            <value>
                <fullName>Promueve al próximo año escolar</fullName>
            </value>
            <value>
                <fullName>Recursará el año escolar</fullName>
            </value>
            <value>
                <fullName>Egresado pero adeuda materias</fullName>
            </value>
            <value>
                <fullName>Graduado en cierre del 3° trimestre</fullName>
            </value>
            <value>
                <fullName>Graduado en mesas de Diciembre</fullName>
            </value>
            <value>
                <fullName>Graduado en mesas de Febrero-Marzo</fullName>
            </value>
            <value>
                <fullName>Graduado en instancias posteriores</fullName>
            </value>
            <value>
                <fullName>Terminó de cursar 5° año, pero adeuda materias</fullName>
            </value>
            <value>
                <fullName>Terminó de cursar 6° año, pero adeuda materias</fullName>
            </value>
            <value>
                <fullName>Promueve a 5° año con materias pendientes</fullName>
            </value>
            <value>
                <fullName>Promueve a 6° año con materias pendientes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seguimiento_Educativo__c/fields/Fecha_de_Informe__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Informe__c</fullName>
    <label>Fecha de Informe</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Seguimiento_Educativo__c/fields/Nro_de_Informe__c.field-meta.xml
<CustomField>
    <fullName>Nro_de_Informe__c</fullName>
    <inlineHelpText>N°0 = Comienzo de año/ N°1 = Julio/ N°2 = Octubre/ N°3 = Diciembre / N°4 = Marzo (con materias adeudadas)</inlineHelpText>
    <label>Nro de Informe</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seguimiento_Educativo__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programa</label>
    <referenceTo>Programa__c</referenceTo>
    <relationshipLabel>Seguimiento Educativo</relationshipLabel>
    <relationshipName>Seguimiento_Educativo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory 
{
    
    public static Programa__c createProgramaNivelCero(String name)
    {
    	id cfc = Schema.SObjectType.Programa__c.getRecordTypeInfosByName().get('Programa Educativo').getRecordTypeId();

		Programa__c programa = new Programa__c(RecordTypeId=cfc, Name=name, N_0_Escuela_Tecnica__c = 'Manzana');
       
		insert programa;
        
        return programa;
    }

    public static Programa__c createProgramaNivelUno(String name)
    {
    	id cfc = Schema.SObjectType.Programa__c.getRecordTypeInfosByName().get('Programa Educativo').getRecordTypeId();

		Programa__c programa = new Programa__c(RecordTypeId=cfc, Name=name, N_1_Escuela_Tecnica_Orientada__c = 'Manzana');
       
		insert programa;
        
        return programa;
    }

    public static Programa__c createProgramaNivelDos(String name)
    {
    	id cfc = Schema.SObjectType.Programa__c.getRecordTypeInfosByName().get('Programa Educativo').getRecordTypeId();

		Programa__c programa = new Programa__c(RecordTypeId=cfc, Name=name, N_2_Escuela_Tecnica__c = 'Manzana', N_2_Escuela_Orientada__c = 'Manzana');
       
		insert programa;
        
        return programa;
    }
    
    public static Pertenencia_a_Programas__c createPertenencia(id idAlumno, id idPrograma)
    {
        Pertenencia_a_Programas__c pertenencia = new Pertenencia_a_Programas__c(Alumno__c=idAlumno,Programa__c=idPrograma, Estado__c='Activo');

		insert pertenencia;
        
        return pertenencia;
    }

    public static Pertenencia_a_Programas__c createPertenenciaInactiva(id idAlumno, id idPrograma)
    {
        Pertenencia_a_Programas__c pertenencia = new Pertenencia_a_Programas__c(Alumno__c=idAlumno,Programa__c=idPrograma, Estado__c='Inactivo');

		insert pertenencia;
        
        return pertenencia;
    }
    
    public static Seguimiento_Educativo__c createSeguimiento(id idAlumno, id idPrograma)
    {
    	Seguimiento_Educativo__c segEduc = new Seguimiento_Educativo__c(
            Alumno__c=idAlumno,
            Estado__c='Cursando 5° Año',
            Nro_de_Informe__c = '4',
            Programa__c=idPrograma,
            Cu_ntas__c=2,
            Fecha_de_Informe__c=Date.newInstance(2021, 2, 17),
            Cantidad_de_Materias_Previas__c=2
            );

		insert segEduc;
        
        return segEduc;
	}

    public static List<Asistencia_a_Espacio_Educativo__c> createAsistenciaEspacios(Id boletin)
    {
        List<Asistencia_a_Espacio_Educativo__c> asistenciaEspacio = new List<Asistencia_a_Espacio_Educativo__c>{ new Asistencia_a_Espacio_Educativo__c(Boletin__c = boletin, Mes__c = 'Mayo', Espacio_Educativo__c = 'Practica Educativa', Cantidad_de_Encuentros__c = 5, Encuentros_Asistidos__c = 5), new Asistencia_a_Espacio_Educativo__c(Boletin__c = boletin, Mes__c = 'Junio', Espacio_Educativo__c = 'Practica Educativa', Cantidad_de_Encuentros__c = 5, Encuentros_Asistidos__c = 5)};

		insert asistenciaEspacio;
        
        return asistenciaEspacio;
	}
    
}